config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index' > create a route
  get 'home/about'
  #root 'home#index'
  
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is Lucas Cabrera"
    @answer = 3 + 4
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :email, class:"form-control",
    placeholder:"youremail@email.com" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone, class:"form-control",
    placeholder:"Phone Nummber" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :twitter, class:"form-control",
    placeholder:"Twitter Account" %>
  </div>

    <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control",
    value:current_user.id, type: :hidden %>
  </div>

  <%= %>


  <br/>
  
  <div class="mb-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr>
  <td>
    <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
  </td>
  <td><%= friend.email %></td>
  <td><%= friend.phone %></td>
  <td>@<%= friend.twitter %></td>
  <td>
    <%= button_to 'Delete', friend, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-sm btn-danger', form: { class: 'd-inline' } %>
  </td>
</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary"  %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<!-- index.html.erb -->
<%if user_signed_in?%>

  <h1>Friends</h1>

    <div id="friends-table" class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Twitter</th>
            <th colspan='2'>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <% if friend.user == current_user%>
            <%= render partial: 'friend', locals: { friend: friend } %>
          <% end %>
          <%end%>
        </tbody>
      </table>
    </div>

    <%= link_to 'New friend', 
        new_friend_path, class:'btn btn-primary' %>

<% else %>

<h1>Hello World!</h1>

<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br/>

<div>
  <%= link_to "Back to friends", friends_path,
      class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<!-- show.html.erb -->
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card">
        <!-- If you have an image for the friend, use that image URL instead of the placeholder -->
        <img src="https://via.placeholder.com/150" class="card-img-top mt-3" alt="Avatar" style="width: 150px; height: 150px; object-fit: cover; border-radius: 50%; margin-left: auto; margin-right: auto;">

        <div class="card-body text-center">
          <h4 class="card-title"><%= @friend.first_name %> <%= @friend.last_name %></h4>
          <p class="card-text"><%= @friend.email %></p>
          <p class="card-text"><%= @friend.phone %></p>
          <p class="card-text">@<%= @friend.twitter %></p>

          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mt-3">
            <%= link_to "Edit this friend", edit_friend_path(@friend), class: 'btn btn-primary' %>
            <%= link_to "Back to friends", friends_path, class: 'btn btn-secondary' %>
            <%= button_to "Delete this friend", @friend, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark ">
  <div class="container-fluid">
  	<%= link_to 'Friends App', 
  		root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About us',
          	  home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit Profile',
                 edit_user_registration_path, class:"nav-link" %>
          </li>

          
          <li class="nav-item">
            <%= link_to 'New Friend',
                new_friend_path, class:"nav-link" %>
          </li>


          <% else %>

        <li class="nav-item">
          <%= link_to 'Sign Up',
              new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign In',
              new_user_session_path, class:"nav-link" %>
        </li>

        <% end %>



      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

<p>	
	<%= @about_me %>
	<%= @answer%>
</p>

app/views/home/index.html.erb
<div class="d-flex justify-content-center">
<h1>Hello, You can change this :) </h1>
</div>
<p></p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>

    <div class="container"> 

    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <br/>
    <%= yield %>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

  </body>
</html>